### ISSUE TITLE
Wrong addon container name

### ISSUE THREAD

**Issue by lukasleitsch** [carstenschroeder/hassio-addons#4]
Thanks for the working remote backup addon.

I used the automation from the readme to start the addon. The name of the addon doesn't work in my Home Assistant. With the Glances addon, I found out the real name of your addon.

If the addon name is unique and the readme is outdated it would be great to update the readme. This automation works for me:

```
- alias: Daily Backup
  id: daily_backup
  trigger:
    platform: time
    at: '22:00:00'
  action:
  - service: hassio.addon_start
    data:
      addon: 36883ed7_remote_backup
```
